<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>Provides helpers for CKomposable engine to ease tests.</Description>
    <LangVersion>11</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppIdentity" Version="1.0.0" />
    <PackageReference Include="CK.Testing.Monitoring" Version="16.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <ProjectReference Include="..\CK.Engine\CK.Engine.csproj" />
  </ItemGroup>
</Project>