
using CK.Core;


namespace CK.Setup
{
    /// <summary>
    /// Extends <see cref="ICSCodeGenerator"/> to provide the <see cref="FinalImplement(IActivityMonitor, ICSCodeGenerationContext)"/>
    /// method. Only few types should need this.
    /// </summary>
    public interface ICSCodeGeneratorWithFinalization : ICSCodeGenerator
    {
        /// <summary>
        /// Called at the end of the code generation before compiling/saving the whole generated code.
        /// No interactions with any other services must be made during finalization. This must only impact
        /// the code generated by this generator.
        /// </summary>
        /// <param name="monitor">The monitor to use.</param>
        /// <param name="codeGenContext">Code generation context with its Dynamic assembly being implemented.</param>
        /// <returns>True on success, false on error. On error, the error must be logged into the <paramref name="monitor"/>.</returns>
        bool FinalImplement( IActivityMonitor monitor, ICSCodeGenerationContext codeGenContext );
    }

}
