
version: build{build}
image: Visual Studio 2019
clone_folder: C:\CKli-World\CK-Database-Projects\CK-StObj
services: mssql2017
branches:
  only:
    - master
    - develop
environment:
  SqlServer/MasterConnectionString: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!
  CKSETUPREMOTESTORE_PUSH_API_KEY:
    secure: ffSyq7zhajO1GUXQraZnZiZGtrPjUMGXXhlS71JUDouxx43VgzbtRfqmZM6zKTmS
  CKSETUP_CAKE_TARGET_STORE_APIKEY_AND_URL:
    secure: ffSyq7zhajO1GUXQraZnZiZGtrPjUMGXXhlS71JUDos5aibfGQQ0zf4BWRjM02dn3zrvVnGZBp6bZwULB/ffASa7PO3mcKcqvppnG6eLYDU=
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
install: []
artifacts:
  - path: '**\*.log'
    name: Log file
  - path: '**\*.trx'
    name: Visual studio test results file
  - path: '**\Tests\**\TestResult*.xml'
    name: NUnit tests result files
  - path: '**Tests\**\Logs\**\*'
    name: Log files
